=== corone-hi/XMLStudy/schema_sample.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">
  
  <xs:element name="news">
    <xs:complexType>
      <xs:sequence>
           <xs:element name="category" type="xs:string"/>
           <xs:element name="topic" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="header" type="headerType" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="body" type="bodyType" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="footer" type="footerType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    
    
    <xs:complexType name="headerType">
      <xs:sequence>
        <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="publishedDate" type="publishedDateType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="reporter" type="reporterType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="publishedDateType">
      <xs:sequence>
        <xs:element name="date" type="dateType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="time" type="timeType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  
  
     <xs:simpleType name="dateType">
      <xs:restriction base="xs:integer">
        <xs:element name="year" type="xs:g Year"/>
        <xs:element name="month" type="xs:gMonth"/>
        <xs:element name="day" type="xs:gDay"/>
      </xs:restriction>
    </xs:simpleType>    

    
    <xs:simpleType name="timeType">
      <xs:restriction base="xs:integer">
       <xs:element type="xs:time"/>
      </xs:restriction>
    </xs:simpleType>

    
    <xs:complexType name="reporterType">
      <xs:sequence>
        <xs:element name="gender" type="genderType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="email" type="emailType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="genderType">
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element name="female" type="xs:string"/>
        <xs:element name="male" type="xs:string"/>
      </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="emailType">
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="email_address" type="xs:anyURI" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
    
    
    <xs:complexType name="bodyType">
      <xs:sequence>
        <xs:element name="sub_title" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="pic" type="picType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="content" type="contentType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="copy-write" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="picType">
      <xs:attribute name="file" type="xs:anyURI" use="required"/>
      <xs:attribute name="title" type="xs:string" use="required"/>
      <xs:attribute name="url" type="xs:string" use="optional"/>
    </xs:complexType>
    
        
    <xs:complexType name="contentType">
      <xs:sequence>
        <xs:element name="p" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="footerType">
      <xs:sequence>
        <xs:element name="related_news" type="relatedType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="keyword" type="keywordType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="relatedType">
      <xs:attribute name="hyperlink" type="xs:anyURI" use="required"/>
  </xs:complexType>
    
    <xs:simpleType name="keywordType">
      <xs:list itemType="string"/>
    </xs:simpleType>
    

</xs:schema>

=== corone-hi/XMLStudy/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="news.css"?>

<news 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="schema_sample.xsd">

            <category>날씨</category>
            <topic>스포츠</topic>
            <header>
                <title>'신영석 15점' 한국, 亞선수권 8강 첫 경기서 대만 완파(종합)</title>
                <publishedDate>
                    <date>
                      <year>2019</year>
                      <month>09</month>
                      <day>17</day> 
                    </date>  
                    <time>19:43:00</time>
                </publishedDate>
                <reporter>
                    <gender>male</gender>
                    <name>하남직 기자</name>
                     <email emailaddress="jiks79@yna.co.kr">jiks79@yna.co.kr</email>
                </reporter>
            </header>

          <body>
            <sub_title>나경복 13점-정지석 12점으로 3-0 완승 앞장..18일 한일전</sub_title>
            <pic file="https://t1.daumcdn.net/news/201909/17/yonhap/20190917194319538ntdv.jpg"  title="한국남자배구 대표팀 센터 신영석(왼쪽) [아시아배구연맹 제공]"  url=""/>
            <content>
                    <p>
                        (서울=연합뉴스) 하남직 기자 = 한국 남자배구가 아시아선수권대회 8강 라운드 첫 경기
                        에서 대만을 완파하며 4강 진출 가능성을 키웠다.          
                    </p>
                    <p>
                        임도헌 감독이 이끄는 한국 대표팀은 17일 이란 테헤란 아자디 스포츠콤플렉스에서 열린
                         제20회 아시아남자배구선수권대회 8강 라운드 F조 1차전에서 대만에 세트 스코어 3-
                         0(25-21 25-19 26-24)으로 승리했다.          
                    </p>
                    <p>
                        한국은 대만과의 역대 전적에서 27승 2패의 절대 우위를 유지했다.
                    </p>
                    <p>
                        D조 예선에서 파키스탄, 쿠웨이트, 인도네시아를 모두 3-0으로 꺾고 조 1위를 차지한 한
                        국은 B조 1위 일본, 2위 대만, D조 2위 파키스탄과 함께 8강 라운드 F조에 묶였다.
                    </p>
                    <p>
                        예선에서 이미 격돌한 파키스탄을 제외한 대만, 일본과 맞붙는 한국은 만만치 않은 상대
                         대만을 누르고 기분 좋게 8강 라운드를 시작했다.
                        대표팀 주장인 센터 신영석(현대캐피탈)이 양 팀 최다인 15점을 뽑으며 팀 승리를 이끌었다.
                    </p>
                    <p>
                        또 '좌우 쌍포'로 나선 정지석(대한항공)과 나경복(우리카드)도 12점과 13점을 사냥하며
                         무실세트 승리에 힘을 보탰다.          
                    </p>
                    <p>
                        주전 세터 황택의(KB손해보험)가 세 세트를 모두 뛰며 경기를 조율했고, 레프트 허수봉
                        (국군체육부대)도 9점을 뽑으며 뒤를 받쳤다.          
                    </p>
                    <p>
                           한국은 특히 신영석, 최민호(현대캐피탈), 김재휘(국군체육부대)가 막강 센터진을 구축해
                          팀 블로킹 득점에서 15-4로 대만을 압도했다.
                          F조에서 1∼4위를 정하면, 8강 라운드 E조 1∼4위와 크로스 토너먼트로 8강전을 펼친다.
                          E조는 이란, 호주, 중국, 인도로 구성했다.       
                    </p>
                    <p>
                        8강에서 이란, 호주, 중국 등 강팀과 맞붙지 않으려면 F조 1위를 차지하는 게 유리하다.
                        이미 이번 대회 8위까지 주는 도쿄올림픽 대륙별 예선 티켓을 손에 넣은 한국은 내심 16년 만의 아시아선수권 정상 탈환도 노린다.
                        한국은 18일 일본과 맞붙는다. 일본전에서 승리하면 F조 1위가 확정된다.          
            </p>      
            </content>
            <copy-write></copy-write>
          </body>
          <footer>
              <related_news hyperlink="http://yna.kr/AKR20190918077200005?input=feed_daum"></related_news>
              <comment></comment>
          </footer>

</news>

=== corone-hi/XMLStudy/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="news.css"?>


<news 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="schema_sample.xsd">
  
      <category>날씨</category>
          <topic>스포츠</topic>
          <header>
            <title>38세 이브라히모비치, LA 시즌 최다골 기록 갈아치웠다</title>
              <publishedDate>
                <date>
                  <year>2019</year>
                  <month>09</month>
                  <day>16</day>  
                </date>  
                <time>15:22 :00</time>
            </publishedDate>
            <reporter>
              <gender>male</gender>
              <name>피주영</name>
              <email emailaddress="akapj@joongang.co.kr">akapj@joongang.co.kr</email>
            </reporter>
          </header>
          
          <body>
          <sub_title>
            켄자스시티전 해트트릭 작성
            26호골 구단 역대 시즌 최다골
            38세에 전성기 하락세 안보여
          </sub_title>
          <pic file="https://imgnews.pstatic.net/image/025/2019/09/16/0002937349_001_20190916152409862.jpg?type=w647"  title="이브라히모비치가 LA갤럭시의 한 시즌 개인 최다골 기록을 갈아치웠다. [사진 LA갤럭시 인스타그램]]"   url=""/>
          <content>
               <p>
                  즐라탄 이브라히모비치(38·LA갤럭시)가 소속팀 개인 최다골 기록을 갈아치웠다.
                  이브라히모비치는 16일(한국시각) 열린 2019 미국프로축구(MLS) 정규리그 스포르팅 켄자스시티
                  와의 경기에서 해트트릭을 터뜨리며 7-2 대승을 이끌었다. 0-1로 뒤진 전반 32분 동점골을 넣은
                   이브라히모비치는 3-1로 앞선 후반 6분엔 쐐기골을 넣었다. 그는 6-1로 승리를 확정한 후반 40분
                    세 번째 골을 기록했다.
            </p>      
            <p>
                    시즌 26호골(25경기) 고지에 오른 이브라히모비치는 LA갤럭시 구단 한 시즌 최다골 기록을 새로
                     썼다. 종전은 2002년 카를로스 루이스의 24골이었다. 이브라히모비치는 미국 무대 첫 시즌인 지
                     난해엔 22골을 기록했다. LA갤럭시 구단 홈페이지는 "이브라히모비치는 입단 후 51경기에서 48골
                      14어시스트를 올렸다"면서 "15경기에서 승리를 안기는 결승골을 터뜨렸다"고 전했다.
            
            </p>
            <p>
                  미국 일간지 LA타임스를 비롯한 현지 언론은 "이브라히모비치가 LA의 기록을 깼다"고 일제히 보
                  도했다. 그는 올 시즌 MLS에서 가장 주목받는 수퍼스타다. 영국 데일리메일은 "38세의 나이에도
                   기량이 떨어질 기미가 전혀 안 보인다"고 감탄했다        
            </p>
            <p>
                1999년 프로에 데뷔한 이브라히모비치는 바르셀로나(스페인)·유벤투스·AC밀란(이상 이탈리아)·
                파리생제르맹(프랑스)·맨유 등을 거치며 세계 정상급 골잡이 반열에 올랐다. 그는 모든 소속팀에
                서 우승컵을 들어올린 덕분에 ‘우승 청부사’로 불린다. 팬들은 그를 ‘이브라카다브라’라고 부르기
                도 한다. 마법사들이 소원을 이뤄주기 위해 외는 마법의 주문 ‘아브라카다브라(Abracadabra)’와
                 그의 이름을 합성해 만든 별명이다.        
            </p>
            <p>
                  불혹을 앞두고 흔들림 없는 그의 득점 비결은 어떤 상황에서도 흐트러지지 않는 슈팅 능력이다.
                   이브라히모비치(1m95㎝)가 큰 키에도 유연성이 좋은 것은 어린 시절 태권도를 수련한 덕분이라
                   고 알려져 있다. 그는 태권도 유단자다. 지난해 9월 기록한 개인 통산 500호 골도 태권도를 연상
                   시키는 돌려차기 오른발 슛으로 뽑아냈다.        
            </p>
            <p>
                  LA 갤럭시 팬들은 불혹을 앞두고도 변함없는 활약을 펼치고 있는 이브라히모비치를 칭찬하기 위
                  해 영화 ‘벤자민 버튼의 시간은 거꾸로 간다’를 거론한다. 이브라히모비치는 2017년 맨체스터 유
                  나이티드(잉글랜드)를 떠나 LA 갤럭시에 입단하면서 나는 여전히 젊다. 마치 영화 주인공 벤자민
                   버튼 같다. 내 나이는 걱정하지 않아도 된다고 말했다. 이 영화에서 80세의 외모를 가지고 태어
                   난 주인공 버튼은 시간이 지날수록 젊어진다.
            
            </p>
          </content>
          <copy-write></copy-write>
        </body>
        <footer>
          <related_news hyperlink="https://news.joins.com/article/23577601?cloc=bulk">"사범님 감옥 넣고 맞게 해주세요" 성폭력 당한 11살의 편지</related_news>
          <comment></comment>
        </footer>
  
  </news>
